In [4]:
import numpy as np
A = np.array([[1,2,3],[3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [5]:
array =np.zeros( (2,3) )
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
array =np.ones( (1,5) )
print(array)

[[1. 1. 1. 1. 1.]]


In [7]:
n = int(input("Kac Adet Sayi Girilecek: "))
a = []
for i in range(0,n):
    elem = int(input("Sayiyi Girin: "))
    a.append(elem)
avg = sum(a) / n
print("Girilen Sayilarin Ortalamasi: ", round(avg,2))

Kac Adet Sayi Girilecek: 2
Sayiyi Girin: 12
Sayiyi Girin: 8
Girilen Sayilarin Ortalamasi:  10.0
